Repository AddstarMC/Prism-Bukkit, pull requests merged in 2020-05, with the labels that each got.

#152 Fix SQL Statements
  src/main/java/me/botsko/prism/database/sql/SQLPrismDataSource.java
  src/main/java/me/botsko/prism/players/PlayerIdentification.java
Labels: discussion wanted

#154 Fix block apply to make it more readable and less complex.
  src/main/java/me/botsko/prism/actions/BlockAction.java
Labels: discussion wanted

#153 Save and restore pandas type
  src/main/java/me/botsko/prism/actions/entity/EntitySerializerFactory.java
  src/main/java/me/botsko/prism/actions/entity/PandaSerializer.java
Labels: enhancement

#155 Properly save liquid type and location when bucket-fill
  src/main/java/me/botsko/prism/listeners/PrismPlayerEvents.java
Labels: bug

#178 Prism bukkit 129
  src/main/java/me/botsko/prism/actionlibs/ActionsQuery.java
  src/main/java/me/botsko/prism/commands/DeleteCommand.java
  src/main/java/me/botsko/prism/database/SelectIdQuery.java
  src/main/java/me/botsko/prism/database/sql/SqlSelectIdQueryBuilder.java
  src/main/java/me/botsko/prism/purge/PurgeChunkingUtil.java
  src/main/java/me/botsko/prism/purge/PurgeTask.java
Labels: enhancement

#182 Prism bukkit 170 - Fix Untracked item movement issue 170
  src/main/java/me/botsko/prism/commands/ReportCommand.java
  src/main/java/me/botsko/prism/listeners/PrismInventoryEvents.java
Labels: Bug -Severe, OP Feedback Requested

#179 Update HikariCP and Paperlib
  pom.xml
  src/main/java/me/botsko/prism/Prism.java
  src/main/java/me/botsko/prism/actions/ActionMeter.java
  src/main/java/me/botsko/prism/actions/EntityAction.java
  src/main/java/me/botsko/prism/commands/TeleportCommand.java
  src/main/java/me/botsko/prism/database/sql/SqlSelectQueryBuilder.java
Labels: enhancement

#177 Supress Paperlib message optionally for those that dislike it.
  src/main/java/me/botsko/prism/Prism.java
Labels: enhancement

#169 Adds Custom names for all blocks that support it.
  src/main/java/me/botsko/prism/actions/BlockAction.java
  src/main/java/me/botsko/prism/listeners/PrismEntityEvents.java
Labels: onhold

#185 Prism bukkit 180 - Paste reporting improvements, Moves joinevent processing async
  src/main/java/me/botsko/prism/listeners/PrismPlayerEvents.java
  src/main/java/me/botsko/prism/players/PlayerIdentification.java
  src/main/resources/plugin.yml
Labels: enhancement

#193 Add tab complete for actions/blocks/entities/worlds
  src/main/java/me/botsko/prism/commandlibs/Flag.java
  src/main/java/me/botsko/prism/commandlibs/PreprocessArgs.java
  src/main/java/me/botsko/prism/parameters/ActionParameter.java
  src/main/java/me/botsko/prism/parameters/BlockParameter.java
  src/main/java/me/botsko/prism/parameters/EntityParameter.java
  src/main/java/me/botsko/prism/parameters/IdParameter.java
  src/main/java/me/botsko/prism/parameters/SimplePrismParameterHandler.java
  src/main/java/me/botsko/prism/parameters/WorldParameter.java
Labels: Component - UI, enhancement
